// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatingCV.Data;

#nullable disable

namespace RatingCV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250307193224_InitialCreate-1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatingCV.Model.cv_ungvien.cv_ungvien", b =>
                {
                    b.Property<int>("ungvienid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ungvienid"));

                    b.Property<string>("dia_chi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("github")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ten_cv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ten_ung_vien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ungvienid");

                    b.ToTable("cv_ungvien", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
